---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: quackforge # change to your domain
  namespace: traefik # add to traefik namespace so it can use it (you DO NOT need it in each app namespace!!!)
spec:
  secretName: quackforge-tls # change to your secretname
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.quackforge.dev" # change to your domain
  dnsNames:
  - "*.quackforge.dev" # change to your domain
  - quackforge.dev # change to your domain
